extends Node

const ITEM_APPLE := "apple"
const ITEM_APPLE_SEED := "apple_seed"
const ITEM_PEAR := "pear"
const ITEM_FERTILIZER := "fertilizer"

const SEED_PRICE := 2
const APPLE_HARVEST_COUNT := 5
const MIN_APPLE_PRICE := 1
const MAX_APPLE_PRICE := 5
const SHOP_APPLE_PRICE_MIN := 1
const SHOP_APPLE_PRICE_MAX := 5
const SHOP_APPLE_STOCK_MIN := 3
const SHOP_APPLE_STOCK_MAX := 12
const STALL_PLAYER_BOUNDARY_HALF_SIZE := 96.0
const STALL_PLAYER_BOUNDARY_WALL_THICKNESS := 16.0
const STALL_CLOSE_HOLD_SECONDS := 1.0
const BEGGING_STOP_HOLD_SECONDS := 1.0
const BEGGING_INFLUENCE_RADIUS := 128.0
const FARM_CLICK_TARGET_RADIUS := 24.0
const FARM_CLICK_REACH_RADIUS := 56.0
const PLAYER_BOUNDARY_COLLISION_LAYER := 16
const PLAYER_WORLD_COLLISION_MASK := 17
const CHENGGUAN_PATROL_SPEED := 70.0
const CHENGGUAN_CHASE_SPEED := 138.0
const CUSTOMER_PURCHASE_WAIT_MIN_SECONDS := 5.0
const CUSTOMER_PURCHASE_WAIT_MAX_SECONDS := 10.0
const SCENE_TRANSITION_SECONDS := 1.0
const SLEEP_TRANSITION_SECONDS := 2.0
const REAL_SECONDS_PER_GAME_MINUTE := 5.0
const DAY_START_MINUTE := 6 * 60
const DAY_END_MINUTE := 24 * 60
const CHENGGUAN_FINE := 8

const SCENE_HOUSE := "house"
const SCENE_HOME := "home"
const SCENE_TOWN := "town"

const TOOL_HOE := "hoe"
const TOOL_SEED := "seed"
const TOOL_WATER := "water"
const TOOL_SICKLE := "sickle"
const TOOL_FERTILIZER := "fertilizer"

const WINDOW_PREP := "prep"
const WINDOW_MORNING := "morning"
const WINDOW_SCHOOL := "school"
const WINDOW_FACTORY := "factory"
const WINDOW_END := "end"

const SPOT_SCHOOL := "school_gate"
const SPOT_FACTORY := "factory_gate"
const SPOT_STREET := "street_stall"
const SPOT_SOUTH_STREET := "south_street"

const CUSTOMER_STUDENT := "student"
const CUSTOMER_WORKER := "worker"
const CUSTOMER_AGE_YOUTH := "youth"
const CUSTOMER_AGE_MIDDLE := "middle"
const CUSTOMER_AGE_ELDER := "elder"
const CUSTOMER_GENDER_MALE := "male"
const CUSTOMER_GENDER_FEMALE := "female"
const CUSTOMER_VISUAL_YOUTH_MALE := "youth_male"
const CUSTOMER_VISUAL_YOUTH_FEMALE := "youth_female"
const CUSTOMER_VISUAL_MIDDLE_MALE := "middle_male"
const CUSTOMER_VISUAL_MIDDLE_FEMALE := "middle_female"
const CUSTOMER_VISUAL_ELDER_MALE := "elder_male"
const CUSTOMER_VISUAL_ELDER_FEMALE := "elder_female"
const CUSTOMER_VISUAL_FEMALE_ELDER := CUSTOMER_VISUAL_ELDER_FEMALE
const CUSTOMER_VISUAL_FEMALE_MIDDLE := CUSTOMER_VISUAL_MIDDLE_FEMALE
const STUDENT_CUSTOMER_VISUAL_VARIANTS := [
	CUSTOMER_VISUAL_YOUTH_MALE,
	CUSTOMER_VISUAL_YOUTH_FEMALE,
]
const WORKER_CUSTOMER_VISUAL_VARIANTS := [
	CUSTOMER_VISUAL_MIDDLE_MALE,
	CUSTOMER_VISUAL_MIDDLE_FEMALE,
]
const RANDOM_CUSTOMER_VISUAL_VARIANTS := [
	CUSTOMER_VISUAL_ELDER_MALE,
	CUSTOMER_VISUAL_ELDER_FEMALE,
]
const CUSTOMER_AGE_LABELS := {
	CUSTOMER_AGE_YOUTH: "少年",
	CUSTOMER_AGE_MIDDLE: "中年",
	CUSTOMER_AGE_ELDER: "老年",
}
const CUSTOMER_GENDER_LABELS := {
	CUSTOMER_GENDER_MALE: "男性",
	CUSTOMER_GENDER_FEMALE: "女性",
}

const WINDOW_LABELS := {
	WINDOW_PREP: "准备",
	WINDOW_MORNING: "上午",
	WINDOW_SCHOOL: "放学",
	WINDOW_FACTORY: "下班",
	WINDOW_END: "日终",
}

const ITEM_LABELS := {
	ITEM_APPLE: "苹果",
	ITEM_APPLE_SEED: "苹果种子",
	ITEM_PEAR: "梨",
	ITEM_FERTILIZER: "肥料",
}

const TOOL_LABELS := {
	TOOL_HOE: "锄头",
	TOOL_SEED: "种子",
	TOOL_WATER: "水壶",
	TOOL_SICKLE: "镰刀",
	TOOL_FERTILIZER: "肥料",
}
